### ISSUE TITLE
CI trigger

### ISSUE THREAD

**Issue by Elexy** [ipfs/infra#464]
This issue is to start the process of triggering the benchmarks from the new CI system.
A sample curl command can be found [here](https://github.com/ipfs/benchmarks/tree/master/runner#start-as-a-daemon)
The benchmark run can be triggered based on a specific commit of the js-ipfs repository. 

As of writing we are still working on publishing the results of the clinic investigations on IPFS and providing a usable url in the response.

Let me know if you need more help

**Comment by eefahy** [comment]
Can you say more about how you see this working? How can CI know when a benchmark is to to be kicked off? On merges to master? On a specific branch? or perhaps a particular tag?

cc: @alanshaw

**Comment by Elexy** [comment]
I'd say, at least run on each merge to *master* 
possibly down the line we could build a way to track performance progress of a PR.

In the case of CircleCI this step would filter as such:
```
workflows:
  version: 2
  build_and_test:
    jobs:
      - step-1
      ...
      - step-3
      - benchmark:
          requires:
            - step-3
          filters:
            branches:
              only: master
      - step-4
```
